### ISSUE TITLE
completed documents not showing as completed

### ISSUE THREAD

**Issue by mscholtz** [washingtontrails/vms#138]
For this WP http://staging.wta.org:6543/workparty/a2eK0000000wLWT/ , I've completed both Medical and Backcountry, but they're both still showing with the "Complete Online" button.

medical form completed: https://cs9.salesforce.com/a2nK0000000KD7K

**Comment by davisagli** [comment]
Oh, shoot...I switched the completion status for those two documents to be based on the Medical Form Date and Backcountry Experience Date rollups on contact which are fetched when the user logs in...but there's no way for pyramid to know that the user has completed the form since logging in. I'll switch it back to fetching the status when the user clicks on the Documents tab (with some misgivings over additional API usage).

**Comment by davisagli** [comment]
Should work now.

**Comment by mscholtz** [comment]
Hmm.  Pretty sure the other wasn't working either.  Without knowing that's
how it had been set up, I had completed those, and logged back in, and
still wasn't showing right...

On Wed, Jun 10, 2015 at 12:03 PM, David Glick <notifications@github.com>
wrote:

> Should work now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/138#issuecomment-110879847>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
Well, does it show correctly now?

**Comment by mscholtz** [comment]
Nope, still not working for me.  Registered for this WP: http://staging.wta.org:6543/workparty/a2eK0000000wL7X/ with this registration: https://cs9.salesforce.com/a2oK0000000vUms and already have backcountry form submitted (https://cs9.salesforce.com/a32K00000006ehy), but still seeing "Complete Online" for backcountry form.

**Comment by davisagli** [comment]
If you go to http://staging.wta.org:6543/workparty/a2eK0000000wL7X/documents.json while logged in, what's the result?

**Comment by davisagli** [comment]
@mscholtz Does it work now? If not, can you please provide the debugging info I requested?

**Comment by mscholtz** [comment]
This works now.  Both documents now show Done with a checkmark.

However, only the Medical form shows a View Document link, and that throws
an err when I click on it:

debug_notfound of url
http://staging.wta.org:6543/workparty/a2eK0000000wL7X/www.google.com;
path_info: u'/workparty/a2eK0000000wL7X/www.google.com', context:
<vms.workparty.WorkParty object at 0x7f42fc1d4910>, view_name: u'
www.google.com', subpath: (), traversed: (u'a2eK0000000wL7X',), root:
<vms.workparty.WorkPartyRoot object at 0x7f42fc11ae90>, vroot:
<vms.workparty.WorkPartyRoot object at 0x7f42fc11ae90>, vroot_path: ()


On Thu, Jun 25, 2015 at 1:17 PM, David Glick <notifications@github.com>
wrote:

> @mscholtz <https://github.com/mscholtz> Does it work now? If not, can you
> please provide the debugging info I requested?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/138#issuecomment-115383925>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
The Required Document has to have a valid URL including the scheme (http/https) in the "Printable Form Link" field.

**Comment by mscholtz** [comment]
Hmm.  Would it be easy on your end to not require the scheme, and assume
it's http if none is given?  The validation in SF on a URL field does not
require it, and does assume http when it composes the link to display
on-screen.

Otherwise, we could create a custom validation rule for the field.

On Fri, Jun 26, 2015 at 2:31 PM, David Glick <notifications@github.com>
wrote:

> The Required Document has to have a valid URL including the scheme
> (http/https) in the "Printable Form Link" field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/washingtontrails/vms/issues/138#issuecomment-115891807>
> .
>



-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by mscholtz** [comment]
Also: I know this was all in the wireframes, but "view document" on a
document shown as completed makes me think that it's going to show me the
document as I filled it out, with my responses.  The Printable Form Link is
not that, will only point at a blank PDF version.  I think we should reword
the link in VMS, maybe to just "printable version"?

On Fri, Jun 26, 2015 at 3:50 PM, Matthew Scholtz <
matthew@percolatorconsulting.com> wrote:

> Hmm.  Would it be easy on your end to not require the scheme, and assume
> it's http if none is given?  The validation in SF on a URL field does not
> require it, and does assume http when it composes the link to display
> on-screen.
>
> Otherwise, we could create a custom validation rule for the field.
>
> On Fri, Jun 26, 2015 at 2:31 PM, David Glick <notifications@github.com>
> wrote:
>
>> The Required Document has to have a valid URL including the scheme
>> (http/https) in the "Printable Form Link" field.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/washingtontrails/vms/issues/138#issuecomment-115891807>
>> .
>>
>
>
>
> --
>
> Matthew Scholtz
> Percolator Consulting
> (206) 289-0816 x3
>
> http://percolatorconsulting.com/
>
>
>


-- 

Matthew Scholtz
Percolator Consulting
(206) 289-0816 x3

http://percolatorconsulting.com/

**Comment by davisagli** [comment]
I guess we could check and add http if necessary when displaying it, but it seems cleaner to add a validation rule so that the data is consistent.

I changed the link to "printable version"

**Comment by mscholtz** [comment]
Done.  Validation rule in place.
