### ISSUE TITLE
Flow Issue when no Email Address/Email Opt Out

### ISSUE THREAD

**Issue by drewpiston** [washingtontrails/vms#517]
Getting email notifications of failures from the Process Builder -- probably because emails can't be sent (because the email address is null or they have opted out of email).

This is (probably) happening on WP Reg confirmation emails with this flow:
VMS Work Party Registration Emails 3.1

**Comment by drewpiston** [comment]
Done! No errors thrown when a WP Registrant doesn't have an email, and the process builder now respects the Email Opt Out field.

**Comment by drewpiston** [comment]
@ebskopin If you want to review this one, just make sure that:
a. The system doesn't throw an error if someone without an email gets registered for a WP
b. If someone with an email registers, but that someone has "Email Opt Out" checked, they don't get a confirmation email.

**Comment by drewpiston** [comment]
@mscholtz  -- actually, I don't think that the Process Builder should respect the Email Opt Out field. I don't think that workflows do that automatically, I think that field is just for use in mass email filtering. Let me know what you think.

**Comment by mscholtz** [comment]
@drewpiston yep, you're right.  I guess it's up to you, @ebskopin and @WaBirder57 .  If someone is flagged Email Opt Out, do you want them to get these emails?

**Comment by WaBirder57** [comment]
Yep you are right,  good catch.  They should still get these emails even if
email opt out is checked .  That is the way it works currently.

Charlie

**Comment by drewpiston** [comment]
Thanks! This is ready for review -- I've taken out the logic that prevented emails to people with Email Opt Out checked.

**Comment by ebskopin** [comment]
Looks good.
